# Generated by Django 3.2.3 on 2021-05-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20210523_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.TextField(default='a'),
        ),
    ]
