# Generated by Django 3.2.3 on 2021-05-23 11:55

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_gender', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_brand', models.TextField(max_length=500)),
                ('medicine_name', models.TextField(max_length=500)),
                ('medicine_price', models.IntegerField()),
                ('medicine_category', models.TextField(max_length=500)),
                ('medicine_usage', models.TextField(max_length=100)),
                ('medicine_side_effect', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='paymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.TextField(max_length=500)),
                ('patient_age', models.IntegerField()),
                ('doctor_fees', models.IntegerField()),
                ('prescription', models.TextField(max_length=1000)),
                ('medicine', jsonfield.fields.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_genderr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.gender')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='doctor.paymentmethod')),
            ],
        ),
    ]
