# Generated by Django 3.2.3 on 2021-05-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_healthrecord_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='patient_genderr',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_gender',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.DeleteModel(
            name='gender',
        ),
    ]
