# Generated by Django 3.2.3 on 2021-05-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20210524_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='payment_method',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.DeleteModel(
            name='paymentMethod',
        ),
    ]
