# Generated by Django 3.2.3 on 2021-05-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20210524_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='medicine',
            field=models.TextField(default='None', max_length=1000),
        ),
    ]
